export type Point = { x: number; y: number };
export type PaletteDefinition = { ink: string; support: string; wash: string; background: string };
export type SceneEvent = { index: number; start: number; end: number; palette: PaletteDefinition; brushStyle: 'dry' | 'wet'; density: number; backgroundFlow: number; seed: number };
export type StrokePoint = Point & { time: number; width: number; opacity: number; color: string; velocity?: Point };
export type StrokeEvent = { id: string; sceneIndex: number; start: number; end: number; points: StrokePoint[]; confidence: number; phraseId?: string };
export type DropEvent = { id: string; sceneIndex: number; time: number; position: Point; radius: number; color: string; strength: number };
export type WashEvent = { id: string; sceneIndex: number; start: number; end: number; position: Point; radius: number; color: string; opacity: number; flow: number };
export type AccentEvent = { time: number; duration?: number; strokeId: string; pressure: number };
export type PaletteKeyframe = { time: number; palette: PaletteDefinition; confidence: number };
export type TrajectoryNote = { start: number; end: number; midi: number; confidence: number; interval: number; x: number; y: number };
export type PhraseCandidateScore = { id: string; score: number; continuity: number; availableSpace: number; directionCompatibility: number; sectionBalance: number; overlap: number; eligible?: boolean; rejectionReason?: string };
export type PhraseDiagnostic = {
  id: string; start: number; end: number; direction: 'ascending' | 'descending' | 'stable' | 'mixed';
  source: 'selected-melody' | 'dsp-fallback'; confidence: number; restThreshold: number;
  boundaryReason: string; placementReason: string; notes: TrajectoryNote[];
  placement?: { candidateId: string; startPosition: Point; endPosition: Point;
    bounds: { left: number; right: number; top: number; bottom: number }; candidates: PhraseCandidateScore[] };
};
export type VisualScore = { version: string; analysisKey: string; trackHash: string; duration: number; scenes: SceneEvent[]; strokes: StrokeEvent[]; drops: DropEvent[]; washes: WashEvent[]; accents: AccentEvent[]; paletteTimeline?: PaletteKeyframe[];
  trajectoryDiagnostics?: { mode: 'phrases'; phrases: PhraseDiagnostic[] } };
